config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'login', to: 'pages#login'
  post 'login', to: 'pages#sessions'
  get 'logout', to: 'pages#logout'
  get 'register', to: 'users#new'

  get 'dashboard', to: 'pages#dashboard'

  resources :users, only: %i[create index]
  resources :transactions, only: :index

  namespace :api do
    get 'withdraw', to: 'transactions#withdraw'
    get 'deposit', to: 'transactions#deposit'
    get 'transfer', to: 'transactions#transfer'
  end

  root 'pages#dashboard'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credit_transaction.rb
# frozen_string_literal: true

class CreditTransaction < Transaction
  default_scope { where(transaction_type: [0, 2]) }

  belongs_to :wallet
  before_save :set_credit_type

  delegate :user, to: :wallet
  validates :amount, numericality: { greater_than: 0 }

  private

  def set_credit_type
    self.tansaction_type ||= 0
  end
end

app/models/debit_transaction.rb
# frozen_string_literal: true

class DebitTransaction < Transaction
  default_scope { where(transaction_type: [1, 3]) }

  belongs_to :wallet
  before_save :set_debit_type

  delegate :user, to: :wallet
  validates :amount, numericality: { greater_than: 0 }

  private

  def set_debit_type
    self.transaction_type ||= 1
  end
end

app/models/transaction.rb
# frozen_string_literal: true

class Transaction < ApplicationRecord
  belongs_to :wallet
  before_save :set_transaction_date, :set_status

  scope :credit_transactions, -> { where(transaction_type: [0, 2]) }
  scope :debit_transactions, -> { where(transaction_type: [1, 3]) }

  enum transaction_type: { credit: 0, debit: 1, withdraw: 2, deposit: 3 }
  enum status: { waiting_for_payment: 0, paid: 1, cancelled: 2, error: 3, refunded: 4, done: 5 }

  validates :amount, numericality: { greater_than: 0 }

  def set_transaction_date
    self.transaction_date = Time.zone.today
  end

  def set_status
    self.status ||= 0
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one :wallet, dependent: :destroy
  has_many :transactions, through: :wallet, dependent: :destroy
  has_many :credit_transactions, lambda {
                                   where(transaction_type: [0, 2])
                                 }, through: :wallet, class_name: 'Transaction', dependent: :destroy
  has_many :debit_transactions, lambda {
                                  where(transaction_type: [1, 3])
                                }, through: :wallet, class_name: 'Transaction', dependent: :destroy

  validates :username, :password, presence: true
  validates :username, uniqueness: true

  before_save :create_wallet

  def wallet_balance
    wallet.total_balance
  end

  delegate :balance, to: :wallet

  private

  def create_wallet
    build_wallet
  end
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  has_many :transactions
  has_many :credit_transactions, -> { where(transaction_type: [0, 2]) }, class_name: 'Transaction', dependent: :destroy
  has_many :debit_transactions, -> { where(transaction_type: [1, 3]) }, class_name: 'Transaction', dependent: :destroy
  belongs_to :user

  before_create :set_default_credit

  def credit_balance
    credit_transactions.sum(:amount)
  end

  def debit_balance
    debit_transactions.sum(:amount)
  end

  def total_balance
    {
      debit: debit_balance,
      credit: credit_balance,
      total: debit_balance - credit_balance + 50_000 # default credit value
    }
  end

  def set_default_credit
    self.balance = 50_000
  end
end

app/controllers/api/transactions_controller.rb
# frozen_string_literal: true

module Api
  class TransactionsController < ApplicationController
    before_action :require_login

    def withdraw
      respond_to do |format|
        Transactions::WithdrawService.new(user: @current_user, amount: params[:amount]).perform
        format.html { redirect_to root_path, notice: 'Withdraw Success' }
        format.json { render json: { status: 200, notice: 'Withdraw Success' }, status: :ok }
      rescue CustomErrors::BalanceNotEnough
        format.html { redirect_to root_path, alert: 'Balance Not Enough' }
        format.json { render json: { status: 200, alert: 'Balance Not Enough' }, status: :ok }
      rescue CustomErrors::AmountMustBePositive
        format.html { redirect_to root_path, alert: 'Amount must be greater than 0' }
        format.json { render json: { status: 200, alert: 'Amount must be greater than 0' }, status: :ok }
      end
    end

    def deposit
      respond_to do |format|
        Transactions::DepositService.new(user: @current_user, amount: params[:amount]).perform
        format.html { redirect_to root_path, notice: 'Deposit Success' }
        format.json { render json: { status: 200, notice: 'Deposit Success' }, status: :ok }
      rescue CustomErrors::AmountMustBePositive
        format.html { redirect_to root_path, alert: 'Amount must be greater than 0' }
        format.json { render json: { status: 200, alert: 'Amount must be greater than 0' }, status: :ok }
      end
    end

    def transfer
      respond_to do |format|
        Transactions::TransferService.new(user: @current_user, amount: params[:amount],
                                          username: params[:username]).perform
        format.html { redirect_to root_path, notice: 'Transfer Success' }
        format.json { render json: { status: 200, notice: 'Transfer Success' }, status: :ok }
      rescue CustomErrors::UserNotFound
        format.html { redirect_to root_path, alert: 'Username Not Found' }
        format.json { render json: { status: 200, alert: 'Username Not Found' }, status: :ok }
      rescue CustomErrors::BalanceNotEnough
        format.html { redirect_to root_path, alert: 'Balance Not Enough' }
        format.json { render json: { status: 200, alert: 'Balance Not Enough' }, status: :ok }
      rescue CustomErrors::AmountMustBePositive
        format.html { redirect_to root_path, alert: 'Amount must be greater than 0' }
        format.json { render json: { status: 200, alert: 'Amount must be greater than 0' }, status: :ok }
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper

  def require_login
    redirect_to login_path if session[:user_id].nil?

    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :require_login, only: :dashboard

  def dashboard
    @balances = @current_user.wallet_balance
    @deposit  = Transaction.new
    @withdraw = Transaction.new
    @transfer = Transaction.new
  end

  def login
    redirect_to dashboard_path unless session[:user].nil?

    @user = User.new
  end

  def sessions
    session[:user_id] = Auth::LoginService.new(params: params[:user]).perform
    redirect_to dashboard_path, notice: 'Successfully logged in'
  rescue StandardError
    redirect_to login_path, alert: 'Invalid credentials'
  end

  def logout
    session[:user] = nil

    redirect_to login_path, notice: 'Sucessfully logged out'
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :require_login

  def index
    @transactions = @current_user.transactions
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    redirect_to root_path unless session[:user].nil?

    @user = User.new
  end

  def create
    @user = Auth::RegisterService.new(params: params[:user]).perform
    redirect_to login_path, notice: 'User was successfully created. Please log in'
  rescue CustomErrors::DuplicateUser
    redirect_to register_path, error: 'Username is already taken'
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(level)
    case level
    when 'success' then 'ui green message'
    when 'alert' then 'ui red message'
    when 'notice' then 'ui blue message'
    end
  end
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags("application", shim: false) %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %> closable">
        <i class="close icon"></i>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.slim
.ui.container
  h1.ui.header.center.aligned
    | Dashboard
  .ui.grid
    .ui.row
      .eight.wide.column
        .ui.centered.card
          .content
            .header
              | User Summary (
              = @current_user.username
              | )
          .content
            h4.ui.sub.header
              | Activities
            .ui.small.feed
              .event
                .content
                  .summary
                    a
                      | Debit              : 
                    = @balances[:debit]
              .event
                .content
                  .summary
                    a
                      | Credit             : 
                    = @balances[:credit]
              .event
                .content
                  .summary
                    a
                      | Current Balance    : 
                    = @balances[:total]
              .event
                .content
                  .summary
                    a
                    = link_to "Click here for list of users", users_path
      .eight.wide.column    
        .ui.centered.card
          .content
            .header
              | Transactions Summary
          .content
            h4.ui.sub.header
              | Activities
            .ui.small.feed
              .event
                .content
                  .summary
                    a
                      | Debit Transactions   : 
                    = @current_user.debit_transactions.size
              .event
                .content
                  .summary
                    a
                      | Credit Transactions  : 
                    = @current_user.credit_transactions.size
              .event
                .content
                  .summary
                    a
                      | Total Transactions   : 
                    = @current_user.transactions.size
              .event
                .content
                  .summary
                    a
                    = link_to "Click here for list of transactions", transactions_path
      br
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Create Deposit
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                    = form_for @deposit, url: url_for(controller: 'api/transactions', action: 'deposit'), method: 'get', html: { class: "ui form" } do |f|
                      .two.fields
                        .field
                          label
                            | Amount
                        .field
                          input[type="text" name="amount" placeholder="Deposit Amount"]
                      = f.submit "Create", name: "deposit", class: "ui blue button"
                      
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Create Withdrawal
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                    = form_for @withdraw, url: url_for(controller: 'api/transactions', action: 'withdraw'), method: 'get', html: { class: "ui form" } do |f|
                      .two.fields
                        .field
                          label
                            | Amount
                        .field
                          input[type="text" name="amount" placeholder="Withdraw Amount"]
                      = f.submit "Create", name: "withdraw", class: "ui blue button"
    .ui.row
    .ui.row
      .column
        .ui.fluid.card
          .content
            .header
              | Transfer to Another User
          .content
            .ui.small.feed
              .event
                .content
                  .summary
                     = form_for @transfer, url: url_for(controller: 'api/transactions', action: 'transfer'), method: 'get', html: { class: "ui form" } do |f|
                      .two.fields
                        .field
                          label
                            | Username
                        .field
                          input[type="text" name="username" placeholder="Username"]
                      .two.fields
                        .field
                          label
                            | Amount
                        .field
                          input[type="text" name="amount" placeholder="Transfer Amount"]
                      = f.submit "Create", name: "transfer", class: "ui blue button"
    .ui.row
    | <button class="ui button" onclick="window.location.href='
    =logout_path
    | '"> Logout 

app/views/pages/login.html.slim
.ui.container
  h1.ui.header.center.aligned
    | Login
  = form_for @user, url: url_for(controller: 'pages', action: 'sessions'), html: {class: "ui form"} do |f|
    .field
      = f.label :username, 'Username'
      = f.text_field :username
    .field
      = f.label :password, 'Password'
      = f.password_field :password
    button.ui.button[type="submit"]
      | Login

app/views/transactions/index.html.slim
.ui.container
  h1.ui.header.center.aligned
    | Transaction List
  .ui.grid
    - @transactions.each do |t|
      .ui.row
        .eight.wide.column
          .ui.centered.fluid.card
            .content
              .header
                = t.transaction_type.capitalize
            .content
              h4.ui.sub.header
                | Detail
              .ui.small.feed
                .event
                  .content
                    .summary
                      a
                        | Amount              : 
                      = t.amount
                .event
                  .content
                    .summary
                      a
                        | Transaction Date    : 
                      = t.transaction_date
    | <button class="ui blue button" onclick="window.location.href='
    =dashboard_path
    | '"> Dashboard 
    

app/views/users/index.html.slim
.ui.container
  h1.ui.header.center.aligned
    | User List
  .ui.grid
    table.ui.celled.table
      thead
        tr
          th
            | Username
          th
            | Balance
      tbody
        - @users.each do |user|
          tr
            td[data-label="Username"]
              = user.username
            td[data-label="Balance"]
              = user.balance
    | <button class="ui blue button" onclick="window.location.href='
    =dashboard_path
    | '"> Dashboard 

app/views/users/new.html.slim
.ui.container
  h1.ui.header.center.aligned
    | Register
  = form_for @user, html: {class: "ui form"} do |f|
    .field
      = f.label :username, 'Username'
      = f.text_field :username
    .field
      = f.label :password, 'Password'
      = f.password_field :password
    button.ui.button[type="submit"]
      | Register